mod project_card;
mod skill_card;
mod contact_form;
mod icons;
mod theme_toggle;
mod header;
mod hero;
mod footer;
mod about;
mod projects;
mod skills;
mod contact;
mod language_switcher;
mod separator;

pub use project_card::ProjectCard;
pub use skill_card::SkillCard;
pub use contact_form::ContactForm;
pub use icons::*;
pub use theme_toggle::ThemeToggle;
pub use header::Header;
pub use hero::Hero;
pub use footer::Footer;
pub use about::About;
pub use projects::Projects;
pub use skills::Skills;
pub use contact::Contact;
pub use language_switcher::LanguageSelector;
pub use separator::Separator;